// BBA pathway data — undergraduate-tuned (foundational certs, 6–18 LPA targets)
export const bbaData = {
  programInfo: {
    title: "BBA — Career Builder",
    tagline: "Foundation-level global certifications for first jobs and 8–18 LPA trajectories",
    duration: "3-year undergraduate program",
    target: "6–18 LPA freshers and early-career roles",
  },
  certs: [
    {
      sno: "B1",
      domain: "Business Analytics & BI",
      name: "Google Data Analytics Professional Certificate",
      provider: "Google / Coursera",
      strength: "Company career certificate",
      costCategory: "Low-cost subscription",
      costINR: "4626",
      time: "3-6 months",
      level: "Beginner",
      skills: "Excel, SQL, Tableau, R, data cleaning, visualization",
      roles: "Junior Data Analyst, Business Analyst Trainee, BI Associate",
      relevance: "4",
      specialization: "BBA Analytics, Marketing",
      artifact: "3 dashboards, SQL queries, end-to-end capstone",
      priority: "High",
      url: "https://www.coursera.org/professional-certificates/google-data-analytics",
    },
    {
      sno: "B2",
      domain: "Business Analytics & BI",
      name: "Microsoft Power BI Data Analyst (PL-300)",
      provider: "Microsoft",
      strength: "Vendor certification",
      costCategory: "Paid exam",
      costINR: "15500",
      time: "2-3 months",
      level: "Intermediate",
      skills: "Power BI, DAX, data modeling, dashboard design",
      roles: "BI Analyst, Reporting Analyst",
      relevance: "5",
      specialization: "BBA Analytics, Finance",
      artifact: "4 Power BI dashboards with DAX measures",
      priority: "High",
      url: "https://learn.microsoft.com/en-us/credentials/certifications/data-analyst-associate/",
    },
    {
      sno: "B3",
      domain: "Digital Marketing & Growth",
      name: "Google Digital Marketing & E-commerce Certificate",
      provider: "Google / Coursera",
      strength: "Company career certificate",
      costCategory: "Low-cost subscription",
      costINR: "4626",
      time: "3-6 months",
      level: "Beginner",
      skills: "SEO, SEM, email marketing, social media, e-commerce",
      roles: "Digital Marketing Associate, Growth Trainee",
      relevance: "4",
      specialization: "BBA Marketing",
      artifact: "Campaign plan, SEO audit, e-commerce store mock",
      priority: "High",
      url: "https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce",
    },
    {
      sno: "B4",
      domain: "Digital Marketing & Growth",
      name: "HubSpot Inbound Marketing Certification",
      provider: "HubSpot Academy",
      strength: "Industry badge",
      costCategory: "Free",
      costINR: "0",
      time: "5-7 hours",
      level: "Beginner",
      skills: "Inbound methodology, content, lead nurturing, CRM basics",
      roles: "Marketing Associate, Content Strategist",
      relevance: "3",
      specialization: "BBA Marketing",
      artifact: "Inbound campaign plan with funnel",
      priority: "High",
      url: "https://academy.hubspot.com/courses/inbound-marketing",
    },
    {
      sno: "B5",
      domain: "Digital Marketing & Growth",
      name: "Google Ads Search Certification",
      provider: "Google Skillshop",
      strength: "Vendor badge",
      costCategory: "Free",
      costINR: "0",
      time: "4-6 hours",
      level: "Beginner",
      skills: "Search ads, bidding, keyword strategy",
      roles: "Performance Marketing Trainee",
      relevance: "4",
      specialization: "BBA Marketing",
      artifact: "Live search campaign plan",
      priority: "High",
      url: "https://skillshop.exceedlms.com/student/path/18128-google-ads-search-certification",
    },
    {
      sno: "B6",
      domain: "Sales, CRM & Revenue Operations",
      name: "Salesforce AI Associate",
      provider: "Salesforce Trailhead",
      strength: "Vendor certification",
      costCategory: "Low-cost / promo",
      costINR: "0",
      time: "1-2 months",
      level: "Beginner",
      skills: "Salesforce platform basics, AI ethics, Einstein basics",
      roles: "Salesforce Admin Trainee, CRM Associate",
      relevance: "4",
      specialization: "BBA Marketing, Operations",
      artifact: "Trailhead Superbadges, demo org",
      priority: "High",
      url: "https://trailhead.salesforce.com/credentials/aiassociate",
    },
    {
      sno: "B7",
      domain: "Sales, CRM & Revenue Operations",
      name: "HubSpot Sales Software Certification",
      provider: "HubSpot Academy",
      strength: "Industry badge",
      costCategory: "Free",
      costINR: "0",
      time: "3-4 hours",
      level: "Beginner",
      skills: "CRM hygiene, sales pipeline, sequences, deals",
      roles: "Sales Development Rep, CRM Coordinator",
      relevance: "3",
      specialization: "BBA Marketing",
      artifact: "Pipeline & sequence in HubSpot demo",
      priority: "High",
      url: "https://academy.hubspot.com/courses/sales-software",
    },
    {
      sno: "B8",
      domain: "Finance, FinTech & FP&A",
      name: "CFI Financial Modeling & Valuation (FMVA) Free Courses",
      provider: "Corporate Finance Institute",
      strength: "Industry recognized",
      costCategory: "Free learning, paid certificate",
      costINR: "0",
      time: "2-3 months",
      level: "Intermediate",
      skills: "3-statement modeling, valuation, Excel, accounting",
      roles: "Finance Analyst Trainee, FP&A Associate",
      relevance: "4",
      specialization: "BBA Finance",
      artifact: "DCF + 3-statement model",
      priority: "High",
      url: "https://corporatefinanceinstitute.com/certifications/fmva-financial-modeling-valuation-analyst/",
    },
    {
      sno: "B9",
      domain: "Finance, FinTech & FP&A",
      name: "Bloomberg Market Concepts (BMC)",
      provider: "Bloomberg",
      strength: "Industry recognized",
      costCategory: "Low-cost",
      costINR: "13500",
      time: "8-12 hours",
      level: "Beginner",
      skills: "Economics, currencies, fixed income, equities",
      roles: "Markets/Research Trainee",
      relevance: "4",
      specialization: "BBA Finance",
      artifact: "Bloomberg BMC certificate + market brief",
      priority: "Medium",
      url: "https://www.bloomberg.com/professional/product/bloomberg-market-concepts/",
    },
    {
      sno: "B10",
      domain: "AI & Business Automation",
      name: "Google AI Essentials",
      provider: "Google / Coursera",
      strength: "Company career certificate",
      costCategory: "Low-cost subscription",
      costINR: "4626",
      time: "8-10 hours",
      level: "Beginner",
      skills: "GenAI for productivity, prompt design, AI ethics",
      roles: "Any role — boosts productivity & differentiation",
      relevance: "4",
      specialization: "All BBA tracks",
      artifact: "Prompt library + AI-augmented project",
      priority: "High",
      url: "https://www.coursera.org/learn/google-ai-essentials",
    },
    {
      sno: "B11",
      domain: "AI & Business Automation",
      name: "Microsoft AI Fundamentals (AI-900)",
      provider: "Microsoft",
      strength: "Vendor certification",
      costCategory: "Paid exam",
      costINR: "8000",
      time: "1-2 months",
      level: "Beginner",
      skills: "AI workloads, Azure ML, responsible AI",
      roles: "AI Associate, Cloud Trainee",
      relevance: "4",
      specialization: "BBA Analytics, Tech",
      artifact: "Azure ML demo + AI use-case deck",
      priority: "High",
      url: "https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/",
    },
    {
      sno: "B12",
      domain: "Project, Product & Agile",
      name: "Google Project Management Certificate",
      provider: "Google / Coursera",
      strength: "Company career certificate",
      costCategory: "Low-cost subscription",
      costINR: "4626",
      time: "3-6 months",
      level: "Beginner",
      skills: "Agile, Scrum, project planning, risk, stakeholder mgmt",
      roles: "Junior PM, Project Coordinator",
      relevance: "4",
      specialization: "BBA Operations, Marketing",
      artifact: "PM portfolio with 2 simulated projects",
      priority: "High",
      url: "https://www.coursera.org/professional-certificates/google-project-management",
    },
    {
      sno: "B13",
      domain: "Operations, Supply Chain & ERP",
      name: "CSSC Six Sigma White & Yellow Belt",
      provider: "Council for Six Sigma Certification",
      strength: "Industry recognized",
      costCategory: "Free / low-cost",
      costINR: "0",
      time: "2-4 weeks",
      level: "Beginner",
      skills: "Lean, DMAIC basics, process mapping",
      roles: "Ops Trainee, Process Associate",
      relevance: "3",
      specialization: "BBA Operations",
      artifact: "DMAIC mini-project, process map",
      priority: "Medium",
      url: "https://www.sixsigmacouncil.org/six-sigma-white-belt-certification/",
    },
    {
      sno: "B14",
      domain: "Consulting, Strategy & Case Skills",
      name: "BCG Strategy Consulting Forage Virtual Experience",
      provider: "Forage / BCG",
      strength: "Industry simulation",
      costCategory: "Free",
      costINR: "0",
      time: "5-8 hours",
      level: "Beginner",
      skills: "Strategy, market sizing, slide-writing, frameworks",
      roles: "Consulting Analyst, Business Analyst",
      relevance: "4",
      specialization: "All BBA tracks",
      artifact: "Forage certificate + 2 consulting case decks",
      priority: "High",
      url: "https://www.theforage.com/virtual-internships/prototype/SKZxezskWgmFjRvj9/Strategy-Consulting-Virtual-Experience",
    },
    {
      sno: "B15",
      domain: "Consulting, Strategy & Case Skills",
      name: "Deloitte Australia Technology Forage",
      provider: "Forage / Deloitte",
      strength: "Industry simulation",
      costCategory: "Free",
      costINR: "0",
      time: "4-6 hours",
      level: "Beginner",
      skills: "Cyber, data, coding basics, advisory skills",
      roles: "Consulting Analyst, Advisory Trainee",
      relevance: "3",
      specialization: "BBA Operations, Finance",
      artifact: "Forage certificate + advisory memo",
      priority: "Medium",
      url: "https://www.theforage.com/virtual-internships/prototype/9PBTqmSxAf6zZTseP/Technology-Job-Simulation",
    },
    {
      sno: "B16",
      domain: "HR, People Analytics & Talent",
      name: "SHRM CP-SCP Foundations / LinkedIn HR Analytics",
      provider: "LinkedIn Learning",
      strength: "Industry recognized",
      costCategory: "Low-cost subscription",
      costINR: "1500",
      time: "1-2 months",
      level: "Beginner",
      skills: "HR analytics, talent acquisition, employee data",
      roles: "HR Trainee, Talent Analyst",
      relevance: "3",
      specialization: "BBA HR",
      artifact: "Attrition dashboard, HR KPI deck",
      priority: "Medium",
      url: "https://www.linkedin.com/learning/paths/become-a-people-analytics-expert",
    },
  ],
  roadmap: [
    {
      domain: "Analytics & BI",
      freeStart: "Google Data Analytics, Excel fundamentals, SQL basics",
      paidAdd: "PL-300, Tableau Specialist",
      portfolio: "3 dashboards, SQL portfolio, KPI memo",
      pitch: "I turn raw data into actionable business insights for my first job.",
    },
    {
      domain: "Digital Marketing",
      freeStart: "HubSpot Inbound, Google Ads Search, GA4",
      paidAdd: "Google Digital Marketing Certificate, Meta Blueprint",
      portfolio: "Campaign plan, SEO audit, content calendar",
      pitch: "I can run live campaigns and measure CAC and conversions.",
    },
    {
      domain: "Sales & CRM",
      freeStart: "HubSpot Sales, Salesforce Trailhead badges",
      paidAdd: "Salesforce AI Associate, Salesforce Admin",
      portfolio: "Pipeline build, demo org, sequence design",
      pitch: "I am CRM-fluent and can support a sales team from day one.",
    },
    {
      domain: "Finance",
      freeStart: "CFI free courses, Excel, accounting basics",
      paidAdd: "Bloomberg BMC, FMVA prep",
      portfolio: "3-statement model, market brief, valuation case",
      pitch: "I have a working finance toolkit, not just textbook knowledge.",
    },
    {
      domain: "AI & Productivity",
      freeStart: "Google AI Essentials, ChatGPT for business",
      paidAdd: "Microsoft AI-900",
      portfolio: "Prompt library + AI-augmented business project",
      pitch: "I use AI to be 2x more productive than my peers.",
    },
    {
      domain: "Project & Product",
      freeStart: "Atlassian Agile basics, Forage PM simulations",
      paidAdd: "Google PM Certificate",
      portfolio: "2 project plans, Jira board, PRD draft",
      pitch: "I can coordinate cross-team delivery as a junior PM.",
    },
    {
      domain: "Operations",
      freeStart: "CSSC White Belt, process mapping basics",
      paidAdd: "CSSC Yellow Belt, Power Platform basics",
      portfolio: "DMAIC mini-project, process map",
      pitch: "I can document and improve real business processes.",
    },
    {
      domain: "Consulting Prep",
      freeStart: "BCG, Deloitte, Accenture Forage simulations",
      paidAdd: "Case interview prep, RocketBlocks",
      portfolio: "3 case decks, consulting writeups",
      pitch: "I can solve business problems and present recommendations.",
    },
  ],
  paths: [
    {
      no: "1",
      role: "Junior Business Analyst",
      mbaFit: "BBA Analytics / Finance / Marketing",
      stack: "Google Data Analytics + PL-300 + SQL + Excel",
      portfolio: "3 dashboards, SQL portfolio, business insight memo",
      employers: "Big 4 audit teams, GCCs, IT services, SaaS analytics",
      ctcLogic: "Fresher BA roles typically start 4–8 LPA; certification + portfolio can push toward 8–12 LPA",
      action: "Weeks 1-6 Power BI, 7-10 SQL, 11-12 portfolio + interviews",
      package: "8–12 LPA",
    },
    {
      no: "2",
      role: "Digital Marketing Associate",
      mbaFit: "BBA Marketing",
      stack: "Google Digital Marketing + HubSpot + Google Ads + GA4",
      portfolio: "Campaign plan, SEO audit, GA4 dashboard",
      employers: "D2C brands, agencies, SaaS, marketplaces",
      ctcLogic: "Fresher roles 4-7 LPA, growth potential to 12-15 LPA in 2 years",
      action: "Build 1 end-to-end campaign + measurement case",
      package: "6–10 LPA",
    },
    {
      no: "3",
      role: "CRM Coordinator / Salesforce Trainee",
      mbaFit: "BBA Marketing / Operations",
      stack: "Salesforce AI Associate + HubSpot Sales + Trailhead badges",
      portfolio: "Demo org, pipeline, process map",
      employers: "Salesforce partners, SaaS, IT services, agencies",
      ctcLogic: "Salesforce certified freshers see 6-12 LPA depending on portfolio",
      action: "Earn 5 Trailhead Superbadges + 1 demo build",
      package: "7–12 LPA",
    },
    {
      no: "4",
      role: "Finance Analyst Trainee",
      mbaFit: "BBA Finance",
      stack: "CFI free + Bloomberg BMC + Excel modeling",
      portfolio: "3-statement model, market brief, valuation case",
      employers: "GCCs, FP&A teams, research firms, fintech",
      ctcLogic: "Finance fresher roles 5-10 LPA, modeling skill raises ceiling",
      action: "Build 1 valuation model + 1 sector brief",
      package: "6–10 LPA",
    },
    {
      no: "5",
      role: "AI-Augmented Business Associate",
      mbaFit: "All BBA tracks",
      stack: "Google AI Essentials + AI-900 + domain certs",
      portfolio: "AI use-case portfolio + automation prototype",
      employers: "Consulting, SaaS, startups, GCCs",
      ctcLogic: "AI-fluent freshers stand out; can land 8-15 LPA roles",
      action: "Build 2 AI-augmented business cases",
      package: "8–15 LPA",
    },
    {
      no: "6",
      role: "Junior Project Coordinator",
      mbaFit: "BBA Operations / Marketing",
      stack: "Google PM Certificate + Jira + Forage",
      portfolio: "PM portfolio with 2 simulated projects",
      employers: "IT services, agencies, SaaS, consulting",
      ctcLogic: "Entry-level PM coordinator roles start 5-9 LPA",
      action: "Run 1 simulated project end-to-end",
      package: "6–9 LPA",
    },
    {
      no: "7",
      role: "Consulting Analyst (Entry)",
      mbaFit: "All BBA tracks",
      stack: "BCG + Deloitte + Accenture Forage + case prep",
      portfolio: "3 case decks, market sizing examples",
      employers: "Tier-2 consulting, Big 4 advisory, boutique firms",
      ctcLogic: "Consulting fresher roles 7-12 LPA; case skills push higher",
      action: "Solve 10 cases + prep 3 consulting decks",
      package: "8–14 LPA",
    },
  ],
  notes: [
    "Designed for undergraduate students targeting 6–18 LPA roles at graduation",
    "Free-first stack: prioritize zero-cost credentials before any paid exam",
    "Build 3 portfolio artifacts before the final placement cycle",
    "Use Forage simulations to demonstrate consulting/tech skills with zero cost",
    "Combine 1 vendor certification + 1 free credential per domain for stronger CV",
  ],
};
